# Generated by Django 3.2.18 on 2023-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuit',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cp',
            field=models.IntegerField(verbose_name='Codigo Postal'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
