# Generated by Django 3.2.18 on 2023-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.BigIntegerField(unique=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.BigIntegerField(unique=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
