# Generated by Django 3.2.18 on 2023-05-14 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0005_auto_20230512_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('cuit', models.BigIntegerField(unique=True, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion Exacta')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('cp', models.IntegerField(verbose_name='Codigo Postal')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfil',
                'managed': True,
            },
        ),
    ]
