# Generated by Django 3.2.18 on 2023-05-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
