# Generated by Django 3.2.18 on 2023-05-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('origen', models.CharField(max_length=50, verbose_name='pais')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='nombre empresa')),
                ('contacto', models.CharField(max_length=50, verbose_name='contacto')),
                ('cargo_contacto', models.CharField(max_length=100, verbose_name='cargo contacto')),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=20, verbose_name='raza')),
                ('tamanio', models.CharField(max_length=20, verbose_name='tamaño')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('formato', models.CharField(max_length=100, verbose_name='formato')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('estado', models.BooleanField(verbose_name='estado')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.raza')),
            ],
        ),
    ]
