# Generated by Django 3.2.18 on 2023-05-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_proveedor_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estado',
            new_name='enStock',
        ),
    ]
