# Generated by Django 3.2.18 on 2023-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_rename_estado_producto_enstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(blank=True, max_length=100, verbose_name='formato'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='tipo'),
        ),
    ]
