# Generated by Django 3.2.18 on 2023-05-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_factura', models.IntegerField(unique=True, verbose_name='Numero Factura')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='total')),
                ('estado', models.CharField(default='verificando', max_length=50, verbose_name='estado')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('cp', models.IntegerField(verbose_name='Codigo Postal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.IntegerField(blank=True, null=True, verbose_name='precio unitario')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('descuento', models.IntegerField(blank=True, default=0, null=True, verbose_name='descuento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
