# Generated by Django 3.2.18 on 2023-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20230608_1207'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(through='carrito.Orden_detalle', to='productos.Producto'),
        ),
    ]
