# Generated by Django 3.2.18 on 2023-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_orden_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='apellido'),
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
    ]
