# Generated by Django 3.2.18 on 2023-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_auto_20230612_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='no_factura',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numero Factura'),
        ),
    ]
