# Generated by Django 3.2.18 on 2023-06-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_orden_no_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_detalle',
            name='subtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='subtotal'),
        ),
    ]
