# Generated by Django 3.2.18 on 2023-05-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230519_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
