# Generated by Django 3.2.18 on 2023-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitulo'),
        ),
    ]
